export const books = [
  {
    id: "beowulf",
    nnTitle: "Beowulf",
    nbTitle: "Beowulf",
    author: "",
    year: 800,
    top: 150,
    left: 0,
  },
  {
    id: "edda",
    nnTitle: "Den eldre Edda",
    nbTitle: "Den eldre Edda",
    author: "",
    year: 900,
    top: 0,
    left: 0,
  },
  {
    id: "rolandskvadet",
    nnTitle: "Rolandskvadet",
    nbTitle: "Rolandskvadet",
    author: "",
    year: 1150,
    top: 395,
    left: 0,
  },
  {
    id: "snorre",
    nnTitle: "Snorres kongesoger",
    nbTitle: "Snorres kongesagaer",
    author: "Snorre",
    year: 1220,
    top: 50,
    left: 0,
  },
  {
    id: "kongespegelen",
    nnTitle: "Kongsspegelen",
    nbTitle: "Kongespeilet",
    author: "",
    year: 1230,
    top: 250,
    left: 0,
  },
  {
    id: "nibelungen",
    nnTitle: "Nibelungen-eposet",
    nbTitle: "Nibelungen-eposet",
    author: "",
    year: 1250,
    top: 350,
    left: 0,
  },
  {
    id: "gunnlaug",
    nnTitle: "Soga om Gunnlaug Ormstunge",
    nbTitle: "Sagaen om Gunnlaug Ormstunge",
    author: "",
    year: 1290,
    top: 150,
    left: 0,
  },
  {
    id: "dekameronen",
    nnTitle: "Dekameronen",
    nbTitle: "Dekameronen",
    author: "",
    year: 1348,
    top: 0,
    left: 0,
  },
  {
    id: "olavogkari",
    nnTitle: "Olav og Kari",
    nbTitle: "Olav og Kari",
    author: "",
    year: 1390,
    top: 75,
    left: 0,
    period: "humanisme",
  },
  {
    id: "draumkvedet",
    nnTitle: "Draumkvedet",
    nbTitle: "Draumkvedet",
    author: "",
    year: 1470,
    top: 0,
    left: 0,
    period: "humanisme",
  },
  {
    id: "vinjeboka",
    nnTitle: "Vinjeboka",
    nbTitle: "Vinjeboka",
    author: "",
    year: 1490,
    top: 400,
    left: 0,
    period: "",
  },
  {
    id: "bergenskapitelsbok",
    nnTitle: "Bergens Kapitelsbok",
    nbTitle: "Bergens Kapitelsbok",
    author: "",
    year: 1552,
    top: 250,
    left: 0,
    period: "",
  },
  {
    id: "dictionarium",
    nnTitle: "Den Norske Dictionarium eller Glosebog",
    nbTitle: "Den Norske Dictionarium eller Glosebog",
    author: "",
    year: 1646,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "floradanica",
    nnTitle: "Flora Danica",
    nbTitle: "Flora Danica",
    author: "",
    year: 1648,
    top: 400,
    left: 0,
    period: "",
  },
  {
    id: "dorothe",
    nnTitle: "Sjælens Sang-Offer",
    nbTitle: "Sjælens Sang-Offer",
    author: "Dorothe Engelbretsdotter",
    year: 1678,
    top: 150,
    left: 0,
    period: "barokk",
  },
  {
    id: "dass",
    nnTitle: "Nordlands Trompet",
    nbTitle: "Nordlands Trompet",
    author: "Petter Dass",
    year: 1690,
    top: 250,
    left: 0,
    period: "",
  },
  {
    id: "kingo",
    nnTitle: "Kingos salmebok",
    nbTitle: "Kingos salmebok",
    author: "Thomas Kingo",
    year: 1699,
    top: 350,
    left: 0,
    period: "",
  },
  {
    id: "nielsklim",
    nnTitle: "Niels Klims underjordiske rejse",
    nbTitle: "Niels Klims underjordiske rejse",
    author: "Ludvig Holberg",
    year: 1741,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "wesselsskrifter",
    nnTitle: "Wessels skrifter",
    nbTitle: "Wessels skrifter",
    author: "Johan Herman Wessel",
    year: 1787,
    top: 350,
    left: 0,
    period: "",
  },
  {
    id: "mauritshansen",
    nnTitle: "Luren",
    nbTitle: "Luren",
    author: "Maurits Christoffer Hansen",
    year: 1819,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "wergeland",
    nnTitle: "Om norsk Sprogreformation",
    nbTitle: "Om norsk Sprogreformation",
    author: "Henrik Wergeland",
    year: 1832,
    top: 80,
    left: 0,
    period: "",
  },
  {
    id: "asbjornsenmoe",
    nnTitle: "Norske folkeeventyr",
    nbTitle: "Norske folkeeventyr",
    author: "Asbjørnsen og Moe",
    year: 1841,
    top: 150,
    left: 0,
    period: "",
  },
  {
    id: "welhaven",
    nnTitle: "Nyere Digte",
    nbTitle: "Nyere Digte",
    author: "Johan Sebastian Welhaven",
    year: 1844,
    top: 220,
    left: 0,
    period: "",
  },
  {
    id: "aasen",
    nnTitle: "Det norske Folkesprogs Grammatik",
    nbTitle: "Det norske Folkesprogs Grammatik",
    author: "Ivar Aasen",
    year: 1848,
    top: 400,
    left: 0,
    period: "",
  },
  {
    id: "bjornson",
    nnTitle: "Faderen",
    nbTitle: "Faderen",
    author: "Bjørnstjerne Bjørnson",
    year: 1848,
    top: 300,
    left: 0,
    period: "",
  },
  {
    id: "collett",
    nnTitle: "Amtmandens Døttre",
    nbTitle: "Amtmandens Døttre",
    author: "Camilla Collett",
    year: 1855,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vinje",
    nnTitle: "Dølen",
    nbTitle: "Dølen",
    author: "Aasmund Olavsson Vinje",
    year: 1858,
    top: 80,
    left: 0,
    period: "",
  },
  {
    id: "knudsen",
    nnTitle: "Unorsk og norsk",
    nbTitle: "Unorsk og norsk",
    author: "Knud Knudsen",
    year: 1880,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "kielland",
    nnTitle: "Gift",
    nbTitle: "Gift",
    author: "Alexander Kielland",
    year: 1883,
    top: 75,
    left: 0,
    period: "",
  },
  {
    id: "garborg",
    nnTitle: "Mannfolk",
    nbTitle: "Mannfolk",
    author: "Arne Garborg",
    year: 1886,
    top: 150,
    left: 0,
    period: "",
  },
  {
    id: "billedbog",
    nnTitle: "Norsk Billedbog for Børn",
    nbTitle: "Norsk Billedbog for Børn",
    author: "",
    year: 1888,
    top: 220,
    left: 0,
    period: "",
  },
  {
    id: "ibsen",
    nnTitle: "Hedda Gabler",
    nbTitle: "Hedda Gabler",
    author: "Henrik Ibsen",
    year: 1890,
    top: 380,
    left: 0,
    period: "",
  },
  {
    id: "krag",
    nnTitle: "Digte",
    nbTitle: "Digte",
    author: "Vilhelm Krag",
    year: 1891,
    top: 75,
    left: 0,
    period: "",
  },
  {
    id: "skram",
    nnTitle: "Forrådt",
    nbTitle: "Forrådt",
    author: "Amalie Skram",
    year: 1892,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "hamsun",
    nnTitle: "Pan",
    nbTitle: "Pan",
    author: "Knut Hamsun",
    year: 1894,
    top: 425,
    left: 0,
    period: "",
  },
  {
    id: "obstfelder",
    nnTitle: "Byen",
    nbTitle: "Byen",
    author: "Sigbjørn Obstfelder",
    year: 1903,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "loland",
    nnTitle: "Kvitebjørnen",
    nbTitle: "Kvitebjørnen",
    author: "Rasmus Løland",
    year: 1906,
    top: 420,
    left: 0,
    period: "",
  },
  {
    id: "frich",
    nnTitle: "Jonas Fjeld",
    nbTitle: "Jonas Fjeld",
    author: "Øvre Richter Frich",
    year: 1911,
    top: 10,
    left: 0,
    period: "",
  },
  {
    id: "undset",
    nnTitle: "Kristin Lavransdatter",
    nbTitle: "Kristin Lavransdatter",
    author: "Sigrid Undset",
    year: 1920,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "falkberget",
    nnTitle: "Bør Børson jr.",
    nbTitle: "Bør Børson jr.",
    author: "Johan Falkberget",
    year: 1920,
    top: 400,
    left: 0,
    period: "",
  },
  {
    id: "nilsen",
    nnTitle: "På stengrunn",
    nbTitle: "På stengrunn",
    author: "Rudolf Nilsen",
    year: 1925,
    top: 250,
    left: 0,
    period: "",
  },
  {
    id: "duun",
    nnTitle: "Medmenneske",
    nbTitle: "Medmenneske",
    author: "Olav Duun",
    year: 1929,
    top: 150,
    left: 0,
    period: "",
  },
  {
    id: "morenvesaas",
    nnTitle: "Harpe og dolk",
    nbTitle: "Harpe og dolk",
    author: "Halldis Moren Vesaas",
    year: 1929,
    top: 75,
    left: 0,
    period: "",
  },
  {
    id: "sandemose",
    nnTitle: "En flyktning krysser sitt spor",
    nbTitle: "En flyktning krysser sitt spor",
    author: "Aksel Sandemose",
    year: 1933,
    top: 370,
    left: 0,
    period: "",
  },
  {
    id: "jacobsen",
    nnTitle: "Jord og jern",
    nbTitle: "Jord og jern",
    author: "Rolf Jacobsen",
    year: 1933,
    top: 210,
    left: 0,
    period: "",
  },
  {
    id: "hoel",
    nnTitle: "Veien til verdens ende",
    nbTitle: "Veien til verdens ende",
    author: "Sigurd Hoel",
    year: 1933,
    top: 300,
    left: 0,
    period: "",
  },
  {
    id: "grieg",
    nnTitle: "Til ungdommen",
    nbTitle: "Til ungdommen",
    author: "Nordahl Grieg",
    year: 1936,
    top: 150,
    left: 0,
    period: "",
  },
  {
    id: "overland",
    nnTitle: "Den røde front",
    nbTitle: "Den røde front",
    author: "Arnulf Øverland",
    year: 1937,
    top: 75,
    left: 0,
    period: "",
  },
  {
    id: "stortingsmelding",
    nnTitle: "Stortingsmelding nr.31",
    nbTitle: "Stortingsmelding nr.31",
    author: "",
    year: 1937,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vangsgutane",
    nnTitle: "Vangsgutane",
    nbTitle: "Vangsgutane",
    author: "",
    year: 1941,
    top: 425,
    left: 0,
    period: "",
  },
  {
    id: "hagerup",
    nnTitle: "Videre",
    nbTitle: "Videre",
    author: "Inger Johanne Hagerup",
    year: 1945,
    top: 45,
    left: 0,
    period: "",
  },
  {
    id: "vesaas",
    nnTitle: "Is-slottet",
    nbTitle: "Is-slottet",
    author: "Tarjei Vesaas",
    year: 1963,
    top: 150,
    left: 0,
    period: "",
  },
  {
    id: "hauge",
    nnTitle: "Dropar i austavind",
    nbTitle: "Dropar i austavind",
    author: "Olav H. Hauge",
    year: 1966,
    top: 60,
    left: 0,
    period: "",
  },
  {
    id: "vold",
    nnTitle: "Mor Godhjertas glade versjon. Ja",
    nbTitle: "Mor Godhjertas glade versjon. Ja",
    author: "Jan Erik Vold",
    year: 1968,
    top: 420,
    left: 0,
    period: "",
  },
  {
    id: "flogstad",
    nnTitle: "Dalen Portland",
    nbTitle: "Dalen Portland",
    author: "Kjartan Fløgstad",
    year: 1977,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "kjarstad",
    nnTitle: "Forføreren",
    nbTitle: "Forføreren",
    author: "Jan Kjærstad",
    year: 1993,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "fosse",
    nnTitle: "Nokon kjem til å komme",
    nbTitle: "Nokon kjem til å komme",
    author: "Jon Fosse",
    year: 1996,
    top: 200,
    left: 0,
    period: "",
  },
  {
    id: "loe",
    nnTitle: "Naiv.Super",
    nbTitle: "Naiv.Super",
    author: "Erlend Loe",
    year: 1996,
    top: 90,
    left: 0,
    period: "",
  },
  {
    id: "orstavik",
    nnTitle: "Kjærlighet",
    nbTitle: "Kjærlighet",
    author: "Hanne Ørstavik",
    year: 1997,
    top: 300,
    left: 0,
    period: "",
  },
  {
    id: "seierstad",
    nnTitle: "Bokhandleren i Kabul",
    nbTitle: "Bokhandleren i Kabul",
    author: "Åsne Seierstad",
    year: 2002,
    top: 30,
    left: 0,
    period: "",
  },
  {
    id: "rehman",
    nnTitle: "Mullaløft",
    nbTitle: "Mullaløft",
    author: "Shabana Rehman",
    year: 2004,
    top: 370,
    left: 0,
    period: "",
  },
  {
    id: "knausgard",
    nnTitle: "Min kamp",
    nbTitle: "Min kamp",
    author: "Karl Ove Knausgård",
    year: 2009,
    top: 100,
    left: 0,
    period: "postmodernisme",
  },
];
