export const books = [
  {
    id: "beowulf",
    nnTitle: "Beowulf",
    nbTitle: "Beowulf",
    author: "Beowulf",
    year: 800,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "edda",
    nnTitle: "Den eldre Edda",
    nbTitle: "Den eldre Edda",
    author: "Edda",
    year: 900,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "rolandskvadet",
    nnTitle: "Rolandskvadet",
    nbTitle: "Rolandskvadet",
    author: "Rolandskvadet",
    year: 1150,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "snorre",
    nnTitle: "Snorres kongesoger",
    nbTitle: "Snorres kongesoger",
    author: "Snorre",
    year: 1220,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "kongespegelen",
    nnTitle: "Kongsspegelen",
    nbTitle: "Kongsspegelen",
    author: "Kongespegelen",
    year: 1230,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "nibelungen",
    nnTitle: "Nibelungen-eposet",
    nbTitle: "Nibelungen-eposet",
    author: "Nibelungen",
    year: 1250,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "gunnlaug",
    nnTitle: "Soga om Gunnlaug Ormstunge",
    nbTitle: "Soga om Gunnlaug Ormstunge",
    author: "Gunnlaug",
    year: 1290,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "dekameronen",
    nnTitle: "Dekameronen",
    nbTitle: "Dekameronen",
    author: "Dekameronen",
    year: 1348,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "olavogkari",
    nnTitle: "Olav og Kari",
    nbTitle: "Olav og Kari",
    author: "OlavOgKari",
    year: 1390,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "draumkvedet",
    nnTitle: "Draumkvedet",
    nbTitle: "Draumkvedet",
    author: "Draumkvedet",
    year: 1470,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vinjeboka",
    nnTitle: "Vinjeboka",
    nbTitle: "Vinjeboka",
    author: "Vinjeboka",
    year: 1490,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "bergenskapitelsbok",
    nnTitle: "Bergens Kapitelsbok",
    nbTitle: "Bergens Kapitelsbok",
    author: "BergensKapitelsbok",
    year: 1552,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "dictionarium",
    nnTitle: "Den Norske Dictionarium eller Glosebog",
    nbTitle: "Den Norske Dictionarium eller Glosebog",
    author: "Dictionarium",
    year: 1646,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "floradanica",
    nnTitle: "Flora Danica",
    nbTitle: "Flora Danica",
    author: "FloraDanica",
    year: 1648,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "dorothe",
    nnTitle: "Sjælens Sang-Offer",
    nbTitle: "Sjælens Sang-Offer",
    author: "Dorothe",
    year: 1678,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "dass",
    nnTitle: "Nordlands Trompet",
    nbTitle: "Nordlands Trompet",
    author: "Dass",
    year: 1690,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "kingo",
    nnTitle: "Kingos salmebok",
    nbTitle: "Kingos salmebok",
    author: "Kingo",
    year: 1699,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "nielsklim",
    nnTitle: "Holberg: Niels Klim",
    nbTitle: "Holberg: Niels Klim",
    author: "NielsKlim",
    year: 1741,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "wesselsskrifter",
    nnTitle: "Wessels skrifter",
    nbTitle: "Wessels skrifter",
    author: "WesselsSkrifter",
    year: 1787,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "mauritshansen",
    nnTitle: "Hansen: Luren",
    nbTitle: "Hansen: Luren",
    author: "MauritsHansen",
    year: 1819,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "wergeland",
    nnTitle: "Wergeland: Om norsk Sprogreformation",
    nbTitle: "Wergeland: Om norsk Sprogreformation",
    author: "Wergeland",
    year: 1832,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "asbjornsenmoe",
    nnTitle: "Asbjørnsen og Moe: Norske folkeeventyr",
    nbTitle: "Asbjørnsen og Moe: Norske folkeeventyr",
    author: "AsbjornsenMoe",
    year: 1841,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "welhaven",
    nnTitle: "Welhaven: Nyere Digte",
    nbTitle: "Welhaven: Nyere Digte",
    author: "Welhaven",
    year: 1844,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "aasen",
    nnTitle: "Aasen: Det norske Folkesprogs Grammatik",
    nbTitle: "Aasen: Det norske Folkesprogs Grammatik",
    author: "Aasen",
    year: 1848,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "bjornson",
    nnTitle: "Bjørnson: Faderen",
    nbTitle: "Bjørnson: Faderen",
    author: "Bjornson",
    year: 1848,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "collett",
    nnTitle: "Collett: Amtmandens Døttre",
    nbTitle: "Collett: Amtmandens Døttre",
    author: "Collett",
    year: 1855,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vinje",
    nnTitle: "Vinje: Dølen",
    nbTitle: "Vinje: Dølen",
    author: "Vinje",
    year: 1858,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "knudsen",
    nnTitle: "Knudsen: Unorsk og norsk",
    nbTitle: "Knudsen: Unorsk og norsk",
    author: "Knudsen",
    year: 1880,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "kielland",
    nnTitle: "Kielland: Gift",
    nbTitle: "Kielland: Gift",
    author: "Kielland",
    year: 1883,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "garborg",
    nnTitle: "Garborg: Mannfolk",
    nbTitle: "Garborg: Mannfolk",
    author: "Garborg",
    year: 1886,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "billedbog",
    nnTitle: "Norsk Billedbog for Børn",
    nbTitle: "Norsk Billedbog for Børn",
    author: "Billedbog",
    year: 1888,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "ibsen",
    nnTitle: "Ibsen: Hedda Gabler",
    nbTitle: "Ibsen: Hedda Gabler",
    author: "Ibsen",
    year: 1890,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "krag",
    nnTitle: "Krag: Digte",
    nbTitle: "Krag: Digte",
    author: "Krag",
    year: 1891,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "skram",
    nnTitle: "Skram: Forrådt",
    nbTitle: "Skram: Forrådt",
    author: "Skram",
    year: 1892,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "hamsun",
    nnTitle: "Hamsun: Pan",
    nbTitle: "Hamsun: Pan",
    author: "Hamsun",
    year: 1894,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "obstfelder",
    nnTitle: "Obstfelder: Byen",
    nbTitle: "Obstfelder: Byen",
    author: "Obstfelder",
    year: 1903,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "loland",
    nnTitle: "Løland: Kvitebjørnen",
    nbTitle: "Løland: Kvitebjørnen",
    author: "Loland",
    year: 1906,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "frich",
    nnTitle: "Frich: Jonas Fjeld",
    nbTitle: "Frich: Jonas Fjeld",
    author: "Frich",
    year: 1911,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "undset",
    nnTitle: "Undset: Kristin Lavransdatter",
    nbTitle: "Undset: Kristin Lavransdatter",
    author: "Undset",
    year: 1920,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "falkberget",
    nnTitle: "Falkberget: Bør Børson jr.",
    nbTitle: "Falkberget: Bør Børson jr.",
    author: "Falkberget",
    year: 1920,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "nilsen",
    nnTitle: "Nilsen: På stengrunn",
    nbTitle: "Nilsen: På stengrunn",
    author: "Nilsen",
    year: 1925,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "duun",
    nnTitle: "Duun: Medmenneske",
    nbTitle: "Duun: Medmenneske",
    author: "Duun",
    year: 1929,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "morenvesaas",
    nnTitle: "Moren Vesaas: Harpe og dolk",
    nbTitle: "Moren Vesaas: Harpe og dolk",
    author: "MorenVesaas",
    year: 1929,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "sandemose",
    nnTitle: "Sandemose: En flyktning krysser sitt spor",
    nbTitle: "Sandemose: En flyktning krysser sitt spor",
    author: "Sandemose",
    year: 1933,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "jacobsen",
    nnTitle: "Jacobsen: Jord og jern",
    nbTitle: "Jacobsen: Jord og jern",
    author: "Jacobsen",
    year: 1933,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "hoel",
    nnTitle: "Hoel: Veien til verdens ende",
    nbTitle: "Hoel: Veien til verdens ende",
    author: "Hoel",
    year: 1933,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "grieg",
    nnTitle: "Nordahl Grieg: Til ungdommen",
    nbTitle: "Nordahl Grieg: Til ungdommen",
    author: "Grieg",
    year: 1936,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "overland",
    nnTitle: "Øverland: Den røde front",
    nbTitle: "Øverland: Den røde front",
    author: "Overland",
    year: 1937,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "stortingsmelding",
    nnTitle: "Stortingsmelding nr.31",
    nbTitle: "Stortingsmelding nr.31",
    author: "Stortingsmelding",
    year: 1937,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vangsgutane",
    nnTitle: "Vangsgutane",
    nbTitle: "Vangsgutane",
    author: "Vangsgutane",
    year: 1941,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "hagerup",
    nnTitle: "Hagerup: Videre",
    nbTitle: "Hagerup: Videre",
    author: "Hagerup",
    year: 1945,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vesaas",
    nnTitle: "Vesaas: Is-slottet",
    nbTitle: "Vesaas: Is-slottet",
    author: "Vesaas",
    year: 1963,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "hauge",
    nnTitle: "Hauge: Dropar i austavind",
    nbTitle: "Hauge: Dropar i austavind",
    author: "Hauge",
    year: 1966,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "vold",
    nnTitle: "Vold: Mor Godhjertas glade versjon. Ja",
    nbTitle: "Vold: Mor Godhjertas glade versjon. Ja",
    author: "Vold",
    year: 1968,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "flogstad",
    nnTitle: "Fløgstad: Dalen Portland",
    nbTitle: "Fløgstad: Dalen Portland",
    author: "Flogstad",
    year: 1977,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "kjarstad",
    nnTitle: "Kjærstad: Forføreren",
    nbTitle: "Kjærstad: Forføreren",
    author: "Kjarstad",
    year: 1993,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "fosse",
    nnTitle: "Fosse: Nokon kjem til å komme",
    nbTitle: "Fosse: Nokon kjem til å komme",
    author: "Fosse",
    year: 1996,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "loe",
    nnTitle: "Loe: Naiv.Super",
    nbTitle: "Loe: Naiv.Super",
    author: "Loe",
    year: 1996,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "orstavik",
    nnTitle: "Ørstavik: Kjærlighet",
    nbTitle: "Ørstavik: Kjærlighet",
    author: "Orstavik",
    year: 1997,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "seierstad",
    nnTitle: "Seierstad: Bokhandleren i Kabul",
    nbTitle: "Seierstad: Bokhandleren i Kabul",
    author: "Seierstad",
    year: 2002,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "rehman",
    nnTitle: "Rehman: Mullaløft",
    nbTitle: "Rehman: Mullaløft",
    author: "Rehman",
    year: 2004,
    top: 0,
    left: 0,
    period: "",
  },
  {
    id: "knausgard",
    nnTitle: "Knausgård: Min kamp",
    nbTitle: "Knausgård: Min kamp",
    author: "Knausgard",
    year: 2009,
    top: 0,
    left: 0,
    period: "",
  },
];
